// develop/terminal-hacker/questions.ts
// Level data for the Terminal Hacker mini-game.
// The "hacking" narrative is just flavor text — every level maps to a real,
// commonly used Linux/bash command so the player is actually practicing the
// terminal while it feels like they're breaching a system.

export interface TerminalLevel {
  id: number;
  title: string;
  narrative: string; // hacker-flavored framing shown above the task
  task: string; // plain instruction of what command to run
  promptPath: string; // cwd shown in the prompt BEFORE this command runs
  cwdAfter: string; // cwd shown in the prompt AFTER a correct answer
  hint: string;
  validAnswers: RegExp[]; // acceptable command patterns (case-insensitive)
  output: string[]; // simulated terminal output lines on success
  xp: number;
}

export const terminalLevels: TerminalLevel[] = [
  {
    id: 1,
    title: "Locate Yourself",
    narrative:
      "You've dropped into a remote shell. Before you touch anything, find out where the connection has landed you.",
    task: "Print the current working directory.",
    promptPath: "~",
    cwdAfter: "~",
    hint: "Three letters. Stands for 'print working directory'.",
    validAnswers: [/^pwd$/i],
    output: ["/home/ghost"],
    xp: 10,
  },
  {
    id: 2,
    title: "Stake Out a Base",
    narrative:
      "Working from the home directory is sloppy — you need your own workspace to operate from.",
    task: "Create a new directory named 'project'.",
    promptPath: "~",
    cwdAfter: "~",
    hint: "mkdir <directory-name>",
    validAnswers: [/^mkdir\s+project\/?$/i],
    output: [],
    xp: 10,
  },
  {
    id: 3,
    title: "Move In",
    narrative: "The base is built. Now move your session inside it.",
    task: "Change into the 'project' directory.",
    promptPath: "~",
    cwdAfter: "~/project",
    hint: "cd <directory-name>",
    validAnswers: [/^cd\s+project\/?$/i],
    output: [],
    xp: 10,
  },
  {
    id: 4,
    title: "Scan the Room",
    narrative: "Before planting anything, check what's already here.",
    task: "List the contents of the current directory.",
    promptPath: "~/project",
    cwdAfter: "~/project",
    hint: "ls (add -la for a detailed view)",
    validAnswers: [/^ls(\s+-l?a?)?$/i],
    output: ["(empty directory)"],
    xp: 10,
  },
  {
    id: 5,
    title: "Plant the File",
    narrative: "Drop an empty file that you'll fill with intel shortly.",
    task: "Create an empty file named 'secrets.txt'.",
    promptPath: "~/project",
    cwdAfter: "~/project",
    hint: "touch <filename>",
    validAnswers: [/^touch\s+secrets\.txt$/i],
    output: [],
    xp: 15,
  },
  {
    id: 6,
    title: "Confirm the Drop",
    narrative: "Verify the file actually landed.",
    task: "List the directory contents again.",
    promptPath: "~/project",
    cwdAfter: "~/project",
    hint: "ls",
    validAnswers: [/^ls(\s+-l?a?)?$/i],
    output: ["secrets.txt"],
    xp: 10,
  },
  {
    id: 7,
    title: "Write the Payload",
    narrative: "An empty file is useless. Write a message into it directly from the shell.",
    task: 'Write "access granted" into secrets.txt.',
    promptPath: "~/project",
    cwdAfter: "~/project",
    hint: 'echo "access granted" > secrets.txt',
    validAnswers: [/^echo\s+["']access granted["']\s*>\s*secrets\.txt$/i],
    output: [],
    xp: 20,
  },
  {
    id: 8,
    title: "Read the Intel",
    narrative: "Confirm the payload actually wrote to disk.",
    task: "Print the contents of secrets.txt.",
    promptPath: "~/project",
    cwdAfter: "~/project",
    hint: "cat <filename>",
    validAnswers: [/^cat\s+secrets\.txt$/i],
    output: ["access granted"],
    xp: 15,
  },
  {
    id: 9,
    title: "Build a Vault",
    narrative: "Evidence like this doesn't sit in the open. Build a folder to bury it in.",
    task: "Create a directory named 'logs'.",
    promptPath: "~/project",
    cwdAfter: "~/project",
    hint: "mkdir logs",
    validAnswers: [/^mkdir\s+logs\/?$/i],
    output: [],
    xp: 10,
  },
  {
    id: 10,
    title: "Bury the Evidence",
    narrative: "Relocate secrets.txt into the vault.",
    task: "Move secrets.txt into the logs directory.",
    promptPath: "~/project",
    cwdAfter: "~/project",
    hint: "mv secrets.txt logs/",
    validAnswers: [/^mv\s+secrets\.txt\s+logs\/?$/i],
    output: [],
    xp: 15,
  },
  {
    id: 11,
    title: "Verify the Vault",
    narrative: "Double-check the file actually made it inside logs.",
    task: "List the contents of the logs directory.",
    promptPath: "~/project",
    cwdAfter: "~/project",
    hint: "ls logs",
    validAnswers: [/^ls\s+logs\/?(\s+-l?a?)?$/i],
    output: ["secrets.txt"],
    xp: 15,
  },
  {
    id: 12,
    title: "Copy for Extraction",
    narrative: "Never move the only copy. Keep a backup outside the vault, ready to exfiltrate.",
    task: "Copy logs/secrets.txt to secrets_backup.txt.",
    promptPath: "~/project",
    cwdAfter: "~/project",
    hint: "cp logs/secrets.txt secrets_backup.txt",
    validAnswers: [/^cp\s+logs\/secrets\.txt\s+secrets_backup\.txt$/i],
    output: [],
    xp: 20,
  },
  {
    id: 13,
    title: "Lock It Down",
    narrative: "Make sure nobody else on the system can read your backup.",
    task: "Change secrets_backup.txt's permissions so only the owner can read and write it (600).",
    promptPath: "~/project",
    cwdAfter: "~/project",
    hint: "chmod 600 <filename>",
    validAnswers: [/^chmod\s+600\s+secrets_backup\.txt$/i],
    output: [],
    xp: 20,
  },
  {
    id: 14,
    title: "Check Your Identity",
    narrative: "Before you go further, confirm which user this session is running as.",
    task: "Print the current logged-in user.",
    promptPath: "~/project",
    cwdAfter: "~/project",
    hint: "whoami",
    validAnswers: [/^whoami$/i],
    output: ["ghost"],
    xp: 10,
  },
  {
    id: 15,
    title: "Review the Trail",
    narrative: "Every command you've run so far has been logged. Check the trail before wiping it.",
    task: "Show your command history.",
    promptPath: "~/project",
    cwdAfter: "~/project",
    hint: "history",
    validAnswers: [/^history$/i],
    output: [
      "1  pwd",
      "2  mkdir project",
      "3  cd project",
      "4  ls",
      "5  touch secrets.txt",
      "6  ls",
      '7  echo "access granted" > secrets.txt',
      "8  cat secrets.txt",
      "9  mkdir logs",
      "10  mv secrets.txt logs/",
      "11  ls logs",
      "12  cp logs/secrets.txt secrets_backup.txt",
      "13  chmod 600 secrets_backup.txt",
      "14  whoami",
    ],
    xp: 15,
  },
  {
    id: 16,
    title: "Erase Your Tracks",
    narrative: "Job's done. Wipe the terminal so nothing's left on screen when you disconnect.",
    task: "Clear the terminal.",
    promptPath: "~/project",
    cwdAfter: "~/project",
    hint: "clear",
    validAnswers: [/^clear$/i],
    output: [],
    xp: 25,
  },
];

export const TOTAL_XP = terminalLevels.reduce((sum, l) => sum + l.xp, 0);