// develop/stack-tower/questions.ts
// 128 unique scenarios covering the four core stack operations a CS/DSA
// learner needs to recognize on sight: Push, Pop, Peek, and Top.
// Each scenario has exactly one correct operation. The UI shows all four
// operations as buttons for every block, so no distractor logic is needed
// here (unlike the time-complexity game, the option set never changes).

export const ALL_OPERATIONS = ["Push", "Pop", "Peek", "Top"] as const;

export type StackOp = (typeof ALL_OPERATIONS)[number];

export interface TowerQuestion {
  id: number;
  scenario: string;
  correct: StackOp;
}

export const towerQuestions: TowerQuestion[] = [
  // ---- PUSH — adding a new element on top ----
  { id: 1, scenario: "Add a new plate on top of the stack of plates.", correct: "Push" },
  { id: 2, scenario: "Call stack.push(x) to add x onto the stack.", correct: "Push" },
  { id: 3, scenario: "Append a new page to your browser history when you visit a link.", correct: "Push" },
  { id: 4, scenario: "Call a function, adding a new frame onto the call stack.", correct: "Push" },
  { id: 5, scenario: "Place a new book on top of the pile.", correct: "Push" },
  { id: 6, scenario: "Insert a new poker chip on top of the stack.", correct: "Push" },
  { id: 7, scenario: "Use list.append(x) on a Python list that's being used as a stack.", correct: "Push" },
  { id: 8, scenario: "Call arr.push(x) on a JavaScript array used as a stack.", correct: "Push" },
  { id: 9, scenario: "Deal a new card face-up onto the discard pile.", correct: "Push" },
  { id: 10, scenario: "Open a new browser tab, adding it to the recently-opened stack.", correct: "Push" },
  { id: 11, scenario: "Add an opening bracket '(' onto the stack while parsing an expression.", correct: "Push" },
  { id: 12, scenario: "Add a new checkpoint onto the undo stack after making an edit.", correct: "Push" },
  { id: 13, scenario: "Insert a new plate at the top of a spring-loaded cafeteria plate dispenser.", correct: "Push" },
  { id: 14, scenario: "Move a new disk onto a peg in the Tower of Hanoi.", correct: "Push" },
  { id: 15, scenario: "Add a new frame onto the stack when entering a recursive call.", correct: "Push" },
  { id: 16, scenario: "Place a new coin on top of a stack of coins.", correct: "Push" },
  { id: 17, scenario: "Save a new state onto the history stack in a game engine.", correct: "Push" },
  { id: 18, scenario: "Insert a new node at the head of a stack implemented as a linked list.", correct: "Push" },
  { id: 19, scenario: "Add a new pancake to the top of the stack.", correct: "Push" },
  { id: 20, scenario: "Call s.push_back(x) to add x onto a vector-backed stack in C++.", correct: "Push" },
  { id: 21, scenario: "Follow a link, adding the new page onto the back-navigation stack.", correct: "Push" },
  { id: 22, scenario: "Add a new tray onto the top of a stack of cafeteria trays.", correct: "Push" },
  { id: 23, scenario: "Call stack.push(node) while performing an iterative depth-first traversal.", correct: "Push" },
  { id: 24, scenario: "Add an entry onto the top of the undo stack in a text editor.", correct: "Push" },
  { id: 25, scenario: "Place a new box on top of a stack of moving boxes.", correct: "Push" },
  { id: 26, scenario: "Insert a new element at the end of an array-backed stack.", correct: "Push" },
  { id: 27, scenario: "Call s.append(x) to add x to the top of a stack simulated with a Python list.", correct: "Push" },
  { id: 28, scenario: "Add a new state to the top of the redo stack after undoing an action.", correct: "Push" },
  { id: 29, scenario: "Stack a new pancake onto the existing tower of pancakes.", correct: "Push" },
  { id: 30, scenario: "Call stack.Push(x) to add x onto a Stack<T> object.", correct: "Push" },
  { id: 31, scenario: "Add a new item into a last-in-first-out storage bin.", correct: "Push" },
  { id: 32, scenario: "Add a new operator onto the operator stack while evaluating an expression.", correct: "Push" },

  // ---- POP — removing the top element ----
  { id: 33, scenario: "Remove and return the top plate from the stack.", correct: "Pop" },
  { id: 34, scenario: "Call stack.pop() to remove and return the top element.", correct: "Pop" },
  { id: 35, scenario: "Click the back button, removing the current page from the history stack.", correct: "Pop" },
  { id: 36, scenario: "Return from a function, removing its frame from the call stack.", correct: "Pop" },
  { id: 37, scenario: "Take the top book off the pile.", correct: "Pop" },
  { id: 38, scenario: "Remove the top poker chip from the stack.", correct: "Pop" },
  { id: 39, scenario: "Call list.pop() on a Python list used as a stack.", correct: "Pop" },
  { id: 40, scenario: "Call arr.pop() on a JavaScript array used as a stack.", correct: "Pop" },
  { id: 41, scenario: "Undo the last action by removing the top entry from the undo stack.", correct: "Pop" },
  { id: 42, scenario: "Match a closing bracket by removing the top '(' off the stack.", correct: "Pop" },
  { id: 43, scenario: "Take the top disk off a peg in the Tower of Hanoi.", correct: "Pop" },
  { id: 44, scenario: "Close a browser tab, removing it from the stack of open tabs.", correct: "Pop" },
  { id: 45, scenario: "Remove the top coin from a stack of coins.", correct: "Pop" },
  { id: 46, scenario: "Revert a game engine action by removing the top state off the history stack.", correct: "Pop" },
  { id: 47, scenario: "Remove the head node from a stack implemented as a linked list.", correct: "Pop" },
  { id: 48, scenario: "Take the top pancake off a stack of pancakes.", correct: "Pop" },
  { id: 49, scenario: "Call s.pop_back() to remove the top item from a vector-backed stack in C++.", correct: "Pop" },
  { id: 50, scenario: "Backtrack by removing the most recently visited node from a DFS stack.", correct: "Pop" },
  { id: 51, scenario: "Undo the most recent edit by removing the last entry off the edit stack.", correct: "Pop" },
  { id: 52, scenario: "Take the top box off a stack of moving boxes.", correct: "Pop" },
  { id: 53, scenario: "Remove the last element from an array-backed stack.", correct: "Pop" },
  { id: 54, scenario: "Call stack.pop() while returning from an iterative depth-first traversal.", correct: "Pop" },
  { id: 55, scenario: "Remove the top item from a last-in-first-out storage bin.", correct: "Pop" },
  { id: 56, scenario: "Take a plate off the top of a spring-loaded plate dispenser.", correct: "Pop" },
  { id: 57, scenario: "Redo an undone action by removing the top entry from the redo stack.", correct: "Pop" },
  { id: 58, scenario: "Call stack.Pop() to remove and return the top element of a Stack<T> object.", correct: "Pop" },
  { id: 59, scenario: "Evaluate an expression by removing the top operator from the operator stack.", correct: "Pop" },
  { id: 60, scenario: "Remove the most recent function call from the call stack as an exception unwinds.", correct: "Pop" },
  { id: 61, scenario: "Take the top pancake off the stack to eat it.", correct: "Pop" },
  { id: 62, scenario: "Call s.removeLast() on a list backing a stack, removing its top item.", correct: "Pop" },
  { id: 63, scenario: "Remove and discard the top card from a discard pile.", correct: "Pop" },
  { id: 64, scenario: "Remove the most recently pushed frame off the recursion stack.", correct: "Pop" },

  // ---- PEEK — viewing the top without removing it (peek()-style APIs) ----
  { id: 65, scenario: "Call stack.peek() to see the top element without removing it.", correct: "Peek" },
  { id: 66, scenario: "Check which plate is currently on top of the stack without taking it off.", correct: "Peek" },
  { id: 67, scenario: "Look at the most recent page in browser history without navigating to it.", correct: "Peek" },
  { id: 68, scenario: "Call s.peek() on a Java Stack object to view its top element.", correct: "Peek" },
  { id: 69, scenario: "Glance at the top book on the pile without lifting it off.", correct: "Peek" },
  { id: 70, scenario: "Check the top poker chip's value without removing it from the stack.", correct: "Peek" },
  { id: 71, scenario: "Call myStack.peek() to inspect the top of a stack without popping it.", correct: "Peek" },
  { id: 72, scenario: "Look at the most recently opened browser tab without closing it.", correct: "Peek" },
  { id: 73, scenario: "Check which bracket is on top of the parsing stack without removing it.", correct: "Peek" },
  { id: 74, scenario: "Call undoStack.peek() to see what the next undo would do without performing it.", correct: "Peek" },
  { id: 75, scenario: "Glance at the top disk on a Tower of Hanoi peg without moving it.", correct: "Peek" },
  { id: 76, scenario: "Check the top coin on a stack of coins without removing it.", correct: "Peek" },
  { id: 77, scenario: "Call s.peek() to preview the next node in a DFS traversal before popping it.", correct: "Peek" },
  { id: 78, scenario: "Look at the top pancake without picking it up.", correct: "Peek" },
  { id: 79, scenario: "Call stack.peek() to inspect the current recursive call's saved state without returning from it.", correct: "Peek" },
  { id: 80, scenario: "Peek at the top box in a stack of moving boxes to read its label.", correct: "Peek" },
  { id: 81, scenario: "Call myStack.Peek() to view the top element of a Stack<T> object.", correct: "Peek" },
  { id: 82, scenario: "Check what the topmost item in a last-in-first-out bin is without removing it.", correct: "Peek" },
  { id: 83, scenario: "Glance at the most recent redo action without applying it.", correct: "Peek" },
  { id: 84, scenario: "Call operatorStack.peek() to check the current top operator during expression evaluation.", correct: "Peek" },
  { id: 85, scenario: "Look at the top card in a discard pile without picking it up.", correct: "Peek" },
  { id: 86, scenario: "Call frame = callStack.peek() to inspect the current frame without unwinding it.", correct: "Peek" },
  { id: 87, scenario: "Peek at the top plate in a spring-loaded dispenser to check if it's clean.", correct: "Peek" },
  { id: 88, scenario: "Call s.peek() to check the most recent history state without reverting to it.", correct: "Peek" },
  { id: 89, scenario: "Glance at the top pancake in the stack to see if it's burnt.", correct: "Peek" },
  { id: 90, scenario: "Check the value at the top of a stack before deciding whether to pop it.", correct: "Peek" },
  { id: 91, scenario: "Call item = stack.peek() to read but not remove the most recent undo checkpoint.", correct: "Peek" },
  { id: 92, scenario: "Look at the top element of a bracket-matching stack without popping it yet.", correct: "Peek" },
  { id: 93, scenario: "Peek at the last pushed frame on the recursion stack to check its local variables.", correct: "Peek" },
  { id: 94, scenario: "Call s.peek() to see what token is next to be matched during parsing.", correct: "Peek" },
  { id: 95, scenario: "Check a box's weight in a stack of moving boxes without lifting it.", correct: "Peek" },
  { id: 96, scenario: "Glance at the top card of a shuffled discard pile without touching it.", correct: "Peek" },

  // ---- TOP — accessing the top without removing it (top()-style APIs) ----
  { id: 97, scenario: "Call s.top() in C++ to access the top element of a stack without removing it.", correct: "Top" },
  { id: 98, scenario: "Read the .top attribute of a stack object to see its topmost value.", correct: "Top" },
  { id: 99, scenario: "Ask \"what's on top of the stack right now?\" without touching anything.", correct: "Top" },
  { id: 100, scenario: "Call stk.top() on a std::stack to get a reference to its top element.", correct: "Top" },
  { id: 101, scenario: "Access stack[-1] on a Python list used as a stack to view its top item.", correct: "Top" },
  { id: 102, scenario: "Call s.top() to check the current top of a stack before deciding whether to push or pop.", correct: "Top" },
  { id: 103, scenario: "Read the top property of a Stack<T> object.", correct: "Top" },
  { id: 104, scenario: "Call stk.top() to get the top element of a std::stack right before calling pop().", correct: "Top" },
  { id: 105, scenario: "Access the .top field of a custom Stack class to view its current topmost node.", correct: "Top" },
  { id: 106, scenario: "Ask what value sits at the top of the stack after a sequence of pushes.", correct: "Top" },
  { id: 107, scenario: "Call value = s.top() to store the current top element in a variable, without removing it.", correct: "Top" },
  { id: 108, scenario: "Read arr[arr.length - 1] to access the top of an array-backed stack.", correct: "Top" },
  { id: 109, scenario: "Call stk.top() on a std::stack<int> to compare it against a target value.", correct: "Top" },
  { id: 110, scenario: "Access the top pointer of a linked-list-backed stack to see which node is topmost.", correct: "Top" },
  { id: 111, scenario: "Call s.top() to check whether it matches the last opened bracket.", correct: "Top" },
  { id: 112, scenario: "Read the top field of a stack node struct to get its stored value.", correct: "Top" },
  { id: 113, scenario: "Call stk.top() to determine what the next popped value would be, without popping.", correct: "Top" },
  { id: 114, scenario: "Access the top of a min-stack implementation to check the current minimum.", correct: "Top" },
  { id: 115, scenario: "Call s.top() right before s.pop() to first retrieve the value about to be removed.", correct: "Top" },
  { id: 116, scenario: "Check the top of a stack of trays to know which tray a customer would grab next.", correct: "Top" },
  { id: 117, scenario: "Call stk.top() to verify the stack is non-empty before further operations.", correct: "Top" },
  { id: 118, scenario: "Access the top of an operator stack to compare operator precedence during parsing.", correct: "Top" },
  { id: 119, scenario: "Call s.top() to return the current top of a stack in a function that must not modify it.", correct: "Top" },
  { id: 120, scenario: "Read the top of a call stack to identify which function is currently executing.", correct: "Top" },
  { id: 121, scenario: "Call stk.top() to check the most recently pushed disk on a Tower of Hanoi peg.", correct: "Top" },
  { id: 122, scenario: "Access the top of a stack used to reverse a string, without removing any characters yet.", correct: "Top" },
  { id: 123, scenario: "Call s.top() on a std::stack<char> to check if it holds an opening bracket.", correct: "Top" },
  { id: 124, scenario: "Read the topmost element of a stack-based calculator before applying an operator.", correct: "Top" },
  { id: 125, scenario: "Call stk.top() to check the current top plate's type in a dispenser simulation.", correct: "Top" },
  { id: 126, scenario: "Access the top of a browser history stack to display the current page's title.", correct: "Top" },
  { id: 127, scenario: "Call s.top() to check a box's label in a stack of moving boxes without removing it.", correct: "Top" },
  { id: 128, scenario: "Read the top of a stack in a text editor to display the most recent, not-yet-undone edit.", correct: "Top" },
];